{% set name = "kitty" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kovidgoyal/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 5190f5eeb4653ac2ca02885623fd3aa10da1c82260c5b9866614ef4fd7427856

build:
  number: 4
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - python
    - dbus  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xineramaproto  # [linux]
    - libglu  # [linux]
    - xorg-glproto  # [linux]
    - mesalib  # [linux]
    - libxkbcommon  # [linux]
    - harfbuzz
    - zlib
    - libpng
    - freetype  # [linux]
    - fontconfig  # [linux]
    - imagemagick
    - pygments
    - libcanberra
    - lcms2
  run:
    - python
    - imagemagick
    - pygments
    - xkeyboard-config
    - libcanberra

test:
  commands:
    - kitty --help

about:
  home: https://sw.kovidgoyal.net/kitty/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A cross-platform, fast, feature full, GPU based terminal emulator
  doc_url: https://sw.kovidgoyal.net/kitty/
  dev_url: https://github.com/kovidgoyal/kitty

extra:
  recipe-maintainers:
    - CJ-Wright
