{% set name = "kitty" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kovidgoyal/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: cbe9724730077c3c0ca52e431ff115c317b198dbf609c843be4aa9f34c2d5412

build:
  number: 0
  skip: true  # [win or py2k or osx]
  ignore_run_exports:
    - imagemagick

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - python
    - dbus  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xineramaproto  # [linux]
    - libglu  # [linux]
    - xorg-glproto  # [linux]
    - mesalib  # [linux]
    - libxkbcommon  # [linux]
    # the following are listed as runtime deps, but seem to be needed at build
    - harfbuzz >=1.5.0
    - zlib
    - libpng
    - freetype  # [linux]
    - fontconfig  # [linux]
    - imagemagick
    - pygments
    - libcanberra
    - lcms2
  run:
    - python
    - harfbuzz >=1.5.0
    - zlib
    - libpng
    - freetype  # [linux]
    - fontconfig  # [linux]
    - imagemagick
    - pygments
    - xkeyboard-config
    - libcanberra
    - lcms2

test:
  commands:
    - kitty --help

about:
  home: https://sw.kovidgoyal.net/kitty/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A cross-platform, fast, feature full, GPU based terminal emulator
  doc_url: https://sw.kovidgoyal.net/kitty/
  dev_url: https://github.com/kovidgoyal/kitty

extra:
  recipe-maintainers:
    - CJ-Wright
