travis:
  secure:
    BINSTAR_TOKEN: IfzUmhmt86NQ+mk7G5y763BZ5v88a4iJlK0cuD2bnqRntD73V0sC0UGyuheflLSUj76U0vLc3wgVAmFAwgOi2f3g2970v7yJfTnnLlMAZVXpqxiNQJotf0wn2Zb8z8Jj5XhygEpmX3trtxqfeKaUS1JEIe9YN1RvmURQspuWpNcMhxqvwwVkxBaYi1Gb0OFA3fcrD0Ndc52eztr6nqvLsx0TFlCwxI62vi7Z/D5/cJxX77ZbnMfWDKzkzDn/Z+i9wAdVX/bloiJMIWB0qMqoy+UsAPgw12/63LDgNdzpT4Txv7AmhV+oLhXBPW5k9kxaw8CE3bD+6FhNwEYHr7JztyQkRki5VJyB3crLYSCfYbo4t2xZp1Sk7PWKVCBXQpUt7y9Nu36P4934mSMjddHXA1cEXILW2wpEcyRRYsXVMdwKMnyLRMJiuslFV7JsMHDYAR7lTtSkpdbIuAWqCj6hJnuOjskNivCfTImCynmxiksENxR0nUpUWNiyp53axPDGIiVhNLPvq16wsoyDAbfTvzVfv2FWeZ+7sSAwq6g+VUTUDzwxjpO/5jljESjxRU9nYdIEbTV36qWXrnN8j3e/+QFE81b3rCm9PJUELh1wRLubLu6McYJOkFVwg1M9N05KFmg182eb/Pf8BTfmPXA3hCTRyXedHi/+dFSHQwSNqkU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
